# The following patch enables conversion webhook for CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourcebindings.work.karmada.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        url: https://karmada-webhook.karmada-system.svc:443/convert
        caBundle: {{caBundle}}
      conversionReviewVersions: ["v1"]
