//
//Copyright 2022 The Karmada Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: service.proto

package service

import (
	context "context"
	pb "github.com/karmada-io/karmada/pkg/estimator/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Estimator_MaxAvailableReplicas_FullMethodName      = "/github.com.karmada_io.karmada.pkg.estimator.service.Estimator/MaxAvailableReplicas"
	Estimator_MaxAvailableComponentSets_FullMethodName = "/github.com.karmada_io.karmada.pkg.estimator.service.Estimator/MaxAvailableComponentSets"
	Estimator_GetUnschedulableReplicas_FullMethodName  = "/github.com.karmada_io.karmada.pkg.estimator.service.Estimator/GetUnschedulableReplicas"
)

// EstimatorClient is the client API for Estimator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EstimatorClient interface {
	MaxAvailableReplicas(ctx context.Context, in *pb.MaxAvailableReplicasRequest, opts ...grpc.CallOption) (*pb.MaxAvailableReplicasResponse, error)
	MaxAvailableComponentSets(ctx context.Context, in *pb.MaxAvailableComponentSetsRequest, opts ...grpc.CallOption) (*pb.MaxAvailableComponentSetsResponse, error)
	GetUnschedulableReplicas(ctx context.Context, in *pb.UnschedulableReplicasRequest, opts ...grpc.CallOption) (*pb.UnschedulableReplicasResponse, error)
}

type estimatorClient struct {
	cc grpc.ClientConnInterface
}

func NewEstimatorClient(cc grpc.ClientConnInterface) EstimatorClient {
	return &estimatorClient{cc}
}

func (c *estimatorClient) MaxAvailableReplicas(ctx context.Context, in *pb.MaxAvailableReplicasRequest, opts ...grpc.CallOption) (*pb.MaxAvailableReplicasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.MaxAvailableReplicasResponse)
	err := c.cc.Invoke(ctx, Estimator_MaxAvailableReplicas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *estimatorClient) MaxAvailableComponentSets(ctx context.Context, in *pb.MaxAvailableComponentSetsRequest, opts ...grpc.CallOption) (*pb.MaxAvailableComponentSetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.MaxAvailableComponentSetsResponse)
	err := c.cc.Invoke(ctx, Estimator_MaxAvailableComponentSets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *estimatorClient) GetUnschedulableReplicas(ctx context.Context, in *pb.UnschedulableReplicasRequest, opts ...grpc.CallOption) (*pb.UnschedulableReplicasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.UnschedulableReplicasResponse)
	err := c.cc.Invoke(ctx, Estimator_GetUnschedulableReplicas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EstimatorServer is the server API for Estimator service.
// All implementations must embed UnimplementedEstimatorServer
// for forward compatibility.
type EstimatorServer interface {
	MaxAvailableReplicas(context.Context, *pb.MaxAvailableReplicasRequest) (*pb.MaxAvailableReplicasResponse, error)
	MaxAvailableComponentSets(context.Context, *pb.MaxAvailableComponentSetsRequest) (*pb.MaxAvailableComponentSetsResponse, error)
	GetUnschedulableReplicas(context.Context, *pb.UnschedulableReplicasRequest) (*pb.UnschedulableReplicasResponse, error)
	mustEmbedUnimplementedEstimatorServer()
}

// UnimplementedEstimatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEstimatorServer struct{}

func (UnimplementedEstimatorServer) MaxAvailableReplicas(context.Context, *pb.MaxAvailableReplicasRequest) (*pb.MaxAvailableReplicasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaxAvailableReplicas not implemented")
}
func (UnimplementedEstimatorServer) MaxAvailableComponentSets(context.Context, *pb.MaxAvailableComponentSetsRequest) (*pb.MaxAvailableComponentSetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaxAvailableComponentSets not implemented")
}
func (UnimplementedEstimatorServer) GetUnschedulableReplicas(context.Context, *pb.UnschedulableReplicasRequest) (*pb.UnschedulableReplicasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnschedulableReplicas not implemented")
}
func (UnimplementedEstimatorServer) mustEmbedUnimplementedEstimatorServer() {}
func (UnimplementedEstimatorServer) testEmbeddedByValue()                   {}

// UnsafeEstimatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EstimatorServer will
// result in compilation errors.
type UnsafeEstimatorServer interface {
	mustEmbedUnimplementedEstimatorServer()
}

func RegisterEstimatorServer(s grpc.ServiceRegistrar, srv EstimatorServer) {
	// If the following call pancis, it indicates UnimplementedEstimatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Estimator_ServiceDesc, srv)
}

func _Estimator_MaxAvailableReplicas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.MaxAvailableReplicasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstimatorServer).MaxAvailableReplicas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Estimator_MaxAvailableReplicas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstimatorServer).MaxAvailableReplicas(ctx, req.(*pb.MaxAvailableReplicasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Estimator_MaxAvailableComponentSets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.MaxAvailableComponentSetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstimatorServer).MaxAvailableComponentSets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Estimator_MaxAvailableComponentSets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstimatorServer).MaxAvailableComponentSets(ctx, req.(*pb.MaxAvailableComponentSetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Estimator_GetUnschedulableReplicas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.UnschedulableReplicasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstimatorServer).GetUnschedulableReplicas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Estimator_GetUnschedulableReplicas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstimatorServer).GetUnschedulableReplicas(ctx, req.(*pb.UnschedulableReplicasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Estimator_ServiceDesc is the grpc.ServiceDesc for Estimator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Estimator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.karmada_io.karmada.pkg.estimator.service.Estimator",
	HandlerType: (*EstimatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MaxAvailableReplicas",
			Handler:    _Estimator_MaxAvailableReplicas_Handler,
		},
		{
			MethodName: "MaxAvailableComponentSets",
			Handler:    _Estimator_MaxAvailableComponentSets_Handler,
		},
		{
			MethodName: "GetUnschedulableReplicas",
			Handler:    _Estimator_GetUnschedulableReplicas_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
