//
//Copyright 2022 The Karmada Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: service.proto

package service

import (
	pb "github.com/karmada-io/karmada/pkg/estimator/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x123github.com.karmada_io.karmada.pkg.estimator.service\x1a pkg/estimator/pb/generated.proto2\xc2\x04\n" +
	"\tEstimator\x12\xb3\x01\n" +
	"\x14MaxAvailableReplicas\x12K.github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableReplicasRequest\x1aL.github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableReplicasResponse\"\x00\x12\xc2\x01\n" +
	"\x19MaxAvailableComponentSets\x12P.github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableComponentSetsRequest\x1aQ.github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableComponentSetsResponse\"\x00\x12\xb9\x01\n" +
	"\x18GetUnschedulableReplicas\x12L.github.com.karmada_io.karmada.pkg.estimator.pb.UnschedulableReplicasRequest\x1aM.github.com.karmada_io.karmada.pkg.estimator.pb.UnschedulableReplicasResponse\"\x00B5Z3github.com/karmada-io/karmada/pkg/estimator/service"

var file_service_proto_goTypes = []any{
	(*pb.MaxAvailableReplicasRequest)(nil),       // 0: github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableReplicasRequest
	(*pb.MaxAvailableComponentSetsRequest)(nil),  // 1: github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableComponentSetsRequest
	(*pb.UnschedulableReplicasRequest)(nil),      // 2: github.com.karmada_io.karmada.pkg.estimator.pb.UnschedulableReplicasRequest
	(*pb.MaxAvailableReplicasResponse)(nil),      // 3: github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableReplicasResponse
	(*pb.MaxAvailableComponentSetsResponse)(nil), // 4: github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableComponentSetsResponse
	(*pb.UnschedulableReplicasResponse)(nil),     // 5: github.com.karmada_io.karmada.pkg.estimator.pb.UnschedulableReplicasResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: github.com.karmada_io.karmada.pkg.estimator.service.Estimator.MaxAvailableReplicas:input_type -> github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableReplicasRequest
	1, // 1: github.com.karmada_io.karmada.pkg.estimator.service.Estimator.MaxAvailableComponentSets:input_type -> github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableComponentSetsRequest
	2, // 2: github.com.karmada_io.karmada.pkg.estimator.service.Estimator.GetUnschedulableReplicas:input_type -> github.com.karmada_io.karmada.pkg.estimator.pb.UnschedulableReplicasRequest
	3, // 3: github.com.karmada_io.karmada.pkg.estimator.service.Estimator.MaxAvailableReplicas:output_type -> github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableReplicasResponse
	4, // 4: github.com.karmada_io.karmada.pkg.estimator.service.Estimator.MaxAvailableComponentSets:output_type -> github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableComponentSetsResponse
	5, // 5: github.com.karmada_io.karmada.pkg.estimator.service.Estimator.GetUnschedulableReplicas:output_type -> github.com.karmada_io.karmada.pkg.estimator.pb.UnschedulableReplicasResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
