# This YAML configuration file is used to enable Dependabot for automated dependency management.
# Dependabot helps keep the project's dependencies up-to-date by automatically creating pull requests
# for outdated dependencies based on the version constraints defined in your project.
# For more information and customization options, please refer to the Dependabot documentation:
# Documentation: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically
# Configuration options: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every week
    interval: "weekly"
    
- package-ecosystem: docker
  directory: /cluster/images/
  schedule:
    interval: weekly

- package-ecosystem: docker
  directory: /cluster/images/
  target-branch: "release-1.9"
  schedule:
    interval: weekly

- package-ecosystem: docker
  directory: /cluster/images/
  target-branch: "release-1.8"
  schedule:
    interval: weekly

- package-ecosystem: docker
  directory: /cluster/images/
  target-branch: "release-1.7"
  schedule:
    interval: weekly
