{{ if .Values.autoscaling.apiServer.enabled }}
{{- $name := include "karmada.name" . -}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}-apiserver
  labels:
    {{- include "karmada.apiServer.serviceMonitor.labels" . | nindent 4}}
  namespace: {{ .Values.serviceMonitor.apiServer.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}-apiserver
  minReplicas: {{ .Values.autoscaling.apiServer.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.apiServer.maxReplicas }}
  metrics:
  {{- range $metric, $config := .Values.autoscaling.apiServer.metrics }}
  - type: Resource
    resource:
      name: {{ $metric }}
      target:
        {{- if $config.targetAverageUtilization }}
        type: Utilization
        averageUtilization: {{ $config.targetAverageUtilization }}
        {{- else if $config.targetAverageValue }}
        type: AverageValue
        averageValue: {{ $config.targetAverageValue }}
        {{- end }}
  {{- end }}
{{- end }}
