apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: echo-op
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: echo
  overrideRules:
    - targetCluster:
        clusterNames:
          - member2
      overriders:
        plaintext:
          - operator: replace
            path: /spec/template/spec/containers/0/env/1/value
            value: "override"
