{{- $name := include "karmada.name" . -}}

{{- if eq .Values.installMode "host" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}-webhook
  namespace: {{ include "karmada.namespace" . }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-webhook
  namespace: {{ include "karmada.namespace" . }}
  labels:
  {{- include "karmada.webhook.labels" . | nindent 4}}
spec:
  replicas: {{ .Values.webhook.replicaCount }}
  selector:
    matchLabels:
      {{- include "karmada.webhook.labels" . | nindent 6}}
  {{- with .Values.webhook.strategy }}
  strategy:
  {{- toYaml . | nindent 8 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.webhook.podAnnotations}}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "karmada.webhook.labels" . | nindent 8}}
        {{- include "karmada.webhook.podLabels" . | nindent 8}}
    spec:
      {{- with .Values.webhook.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $name }}-webhook
      {{- with .Values.webhook.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.tolerations}}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $name }}-webhook
          image: {{ .Values.webhook.image.repository}}:{{ .Values.webhook.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
          command:
            - /bin/karmada-webhook
            - --kubeconfig=/etc/kubeconfig
            - --bind-address=0.0.0.0
            - --secure-port=8443
            - --cert-dir=/var/serving-cert
          ports:
            - containerPort: 8443
          volumeMounts:
          {{- include "karmada.kubeconfig.volumeMount" . | nindent 12 }}
            - name: {{ $name }}-webhook-cert-secret
              mountPath: /var/serving-cert
              readOnly: true
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8443
              scheme: HTTPS
      volumes:
      {{- include "karmada.kubeconfig.volume" . | nindent 8}}
        - name: {{ $name }}-webhook-cert-secret
          secret:
            secretName: {{ $name }}-webhook-cert
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-webhook
  namespace: {{ include "karmada.namespace" . }}
spec:
  selector:
    {{- include "karmada.webhook.podLabels" . | nindent 8}}
    app: {{ $name }}-webhook
  ports:
    - port: 443
      targetPort: 8443

{{- end }}
