{{- if and (eq .Values.installMode "host") (eq .Values.certs.mode "custom") }}
{{- $name := include "karmada.name" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-kubeconfig
  namespace: {{ include "karmada.namespace" . }}
stringData:
  kubeconfig: |-
    apiVersion: v1
    kind: Config
    clusters:
      - cluster:
          certificate-authority-data: {{ b64enc .Values.certs.custom.caCrt }}
          insecure-skip-tls-verify: false
          server: https://{{ $name }}-apiserver.{{ include "karmada.namespace" . }}.svc.{{ .Values.clusterDomain }}:5443
        name: {{ $name }}-apiserver
    users:
      - user:
          client-certificate-data: {{ b64enc .Values.certs.custom.crt }}
          client-key-data: {{ b64enc .Values.certs.custom.key }}
        name: {{ $name }}-apiserver
    contexts:
      - context:
          cluster: {{ $name }}-apiserver
          user: {{ $name }}-apiserver
        name: {{ $name }}-apiserver
    current-context: {{ $name }}-apiserver
{{- end }}
