resources:
- bases/multicluster.x-k8s.io_serviceexports.yaml
- bases/multicluster.x-k8s.io_serviceimports.yaml
- bases/policy.karmada.io_clusteroverridepolicies.yaml
- bases/policy.karmada.io_clusterpropagationpolicies.yaml
- bases/policy.karmada.io_federatedresourcequotas.yaml
- bases/policy.karmada.io_overridepolicies.yaml
- bases/policy.karmada.io_propagationpolicies.yaml
- bases/work.karmada.io_resourcebindings.yaml
- bases/work.karmada.io_clusterresourcebindings.yaml
- bases/work.karmada.io_works.yaml
- bases/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
- bases/networking.karmada.io_multiclusteringresses.yaml

patchesStrategicMerge:
- patches/webhook_in_resourcebindings.yaml
- patches/webhook_in_clusterresourcebindings.yaml
