//
//Copyright The Karmada Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: pkg/estimator/pb/estimator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "k8s.io/api/core/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Component defines the scheduling and resource requirements for a single
// workload component (e.g., JobManager, TaskManager).
type Component struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the identifier of the component within the workload set.
	// +required
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// ReplicaRequirements specifies the per-replica resource requirements
	// (CPU, memory, etc.) and scheduling constraints.
	// +required
	ReplicaRequirements *ComponentReplicaRequirements `protobuf:"bytes,2,opt,name=replicaRequirements,proto3" json:"replicaRequirements,omitempty"`
	// Replicas is the number of replicas of this component required in a single workload set.
	// +required
	Replicas      int32 `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_pkg_estimator_pb_estimator_proto_rawDescGZIP(), []int{0}
}

func (x *Component) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Component) GetReplicaRequirements() *ComponentReplicaRequirements {
	if x != nil {
		return x.ReplicaRequirements
	}
	return nil
}

func (x *Component) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

// ComponentReplicaRequirements represents the resource and scheduling requirements for each replica.
type ComponentReplicaRequirements struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NodeClaim represents the NodeAffinity, NodeSelector and Tolerations required by each replica.
	// +optional
	NodeClaim *NodeClaim `protobuf:"bytes,1,opt,name=nodeClaim,proto3,oneof" json:"nodeClaim,omitempty"`
	// ResourceRequest represents the resources required by each replica.
	// Deprecated: Writers should set this field and resourceRequestBytes. Readers should prefer resourceRequestBytes if set.
	// +optional
	//
	// Deprecated: Marked as deprecated in pkg/estimator/pb/estimator.proto.
	ResourceRequest map[string]*resource.Quantity `protobuf:"bytes,2,rep,name=resourceRequest,proto3" json:"resourceRequest,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// PriorityClassName represents the priority class name for a given ResourceRequest.
	// It is used by the resource quota estimator to check quota constraints, as ResourceQuota supports priority class as a scope.
	// +optional
	PriorityClassName string `protobuf:"bytes,3,opt,name=priorityClassName,proto3" json:"priorityClassName,omitempty"`
	// ResourceRequestBytes represents the resources required by each replica.
	// The value of map resourceRequestBytes is a proto-serialized resource.Quantity object.
	// Generated by calling resource.Quantity#Marshal().
	// Convertible to a resource.Quantity object by calling resource.Quantity#Unmarshal().
	// +optional
	ResourceRequestBytes map[string][]byte `protobuf:"bytes,4,rep,name=resourceRequestBytes,proto3" json:"resourceRequestBytes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ComponentReplicaRequirements) Reset() {
	*x = ComponentReplicaRequirements{}
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentReplicaRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentReplicaRequirements) ProtoMessage() {}

func (x *ComponentReplicaRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentReplicaRequirements.ProtoReflect.Descriptor instead.
func (*ComponentReplicaRequirements) Descriptor() ([]byte, []int) {
	return file_pkg_estimator_pb_estimator_proto_rawDescGZIP(), []int{1}
}

func (x *ComponentReplicaRequirements) GetNodeClaim() *NodeClaim {
	if x != nil {
		return x.NodeClaim
	}
	return nil
}

// Deprecated: Marked as deprecated in pkg/estimator/pb/estimator.proto.
func (x *ComponentReplicaRequirements) GetResourceRequest() map[string]*resource.Quantity {
	if x != nil {
		return x.ResourceRequest
	}
	return nil
}

func (x *ComponentReplicaRequirements) GetPriorityClassName() string {
	if x != nil {
		return x.PriorityClassName
	}
	return ""
}

func (x *ComponentReplicaRequirements) GetResourceRequestBytes() map[string][]byte {
	if x != nil {
		return x.ResourceRequestBytes
	}
	return nil
}

// MaxAvailableComponentSetsRequest is the gRPC request message used to estimate
// how many complete sets of components can be scheduled on a cluster.
type MaxAvailableComponentSetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cluster is the target cluster where the scheduling estimation is performed.
	// +required
	Cluster string `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// Components lists the component types that form one full workload set,
	// along with their resource and replica requirements.
	// +required
	Components []*Component `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	// Namespace is the namespace of the workload being estimated.
	// It is used by the accurate estimator to check the quota configurations
	// in the target member cluster.
	// +required
	Namespace     string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxAvailableComponentSetsRequest) Reset() {
	*x = MaxAvailableComponentSetsRequest{}
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxAvailableComponentSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxAvailableComponentSetsRequest) ProtoMessage() {}

func (x *MaxAvailableComponentSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxAvailableComponentSetsRequest.ProtoReflect.Descriptor instead.
func (*MaxAvailableComponentSetsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_estimator_pb_estimator_proto_rawDescGZIP(), []int{2}
}

func (x *MaxAvailableComponentSetsRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *MaxAvailableComponentSetsRequest) GetComponents() []*Component {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *MaxAvailableComponentSetsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// MaxAvailableComponentSetsResponse is the gRPC response message containing the
// maximum number of complete component sets that can be scheduled.
type MaxAvailableComponentSetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MaxSets is the maximum number of workload sets (i.e., all required components together)
	// that the target cluster can accommodate given the resource constraints.
	// +required
	MaxSets       int32 `protobuf:"varint,1,opt,name=maxSets,proto3" json:"maxSets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxAvailableComponentSetsResponse) Reset() {
	*x = MaxAvailableComponentSetsResponse{}
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxAvailableComponentSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxAvailableComponentSetsResponse) ProtoMessage() {}

func (x *MaxAvailableComponentSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxAvailableComponentSetsResponse.ProtoReflect.Descriptor instead.
func (*MaxAvailableComponentSetsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_estimator_pb_estimator_proto_rawDescGZIP(), []int{3}
}

func (x *MaxAvailableComponentSetsResponse) GetMaxSets() int32 {
	if x != nil {
		return x.MaxSets
	}
	return 0
}

// MaxAvailableReplicasRequest represents the request that sent by gRPC client to calculate max available replicas.
type MaxAvailableReplicasRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cluster represents the cluster name.
	// +required
	Cluster string `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// ReplicaRequirements represents the resource and scheduling requirements for each replica.
	// +required
	ReplicaRequirements *ReplicaRequirements `protobuf:"bytes,2,opt,name=replicaRequirements,proto3" json:"replicaRequirements,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MaxAvailableReplicasRequest) Reset() {
	*x = MaxAvailableReplicasRequest{}
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxAvailableReplicasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxAvailableReplicasRequest) ProtoMessage() {}

func (x *MaxAvailableReplicasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxAvailableReplicasRequest.ProtoReflect.Descriptor instead.
func (*MaxAvailableReplicasRequest) Descriptor() ([]byte, []int) {
	return file_pkg_estimator_pb_estimator_proto_rawDescGZIP(), []int{4}
}

func (x *MaxAvailableReplicasRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *MaxAvailableReplicasRequest) GetReplicaRequirements() *ReplicaRequirements {
	if x != nil {
		return x.ReplicaRequirements
	}
	return nil
}

// MaxAvailableReplicasResponse represents the response that sent by gRPC server to calculate max available replicas.
type MaxAvailableReplicasResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MaxReplicas represents the max replica that the cluster can produce.
	// +required
	MaxReplicas   int32 `protobuf:"varint,1,opt,name=maxReplicas,proto3" json:"maxReplicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxAvailableReplicasResponse) Reset() {
	*x = MaxAvailableReplicasResponse{}
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxAvailableReplicasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxAvailableReplicasResponse) ProtoMessage() {}

func (x *MaxAvailableReplicasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxAvailableReplicasResponse.ProtoReflect.Descriptor instead.
func (*MaxAvailableReplicasResponse) Descriptor() ([]byte, []int) {
	return file_pkg_estimator_pb_estimator_proto_rawDescGZIP(), []int{5}
}

func (x *MaxAvailableReplicasResponse) GetMaxReplicas() int32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

// NodeClaim represents the NodeAffinity, NodeSelector and Tolerations required by each replica.
type NodeClaim struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A node selector represents the union of the results of one or more label queries over a set of
	// nodes; that is, it represents the OR of the selectors represented by the node selector terms.
	// Note that only PodSpec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution
	// is included here because it has a hard limit on pod scheduling.
	// Deprecated: Writers should set this field and nodeAffinityBytes. Readers should prefer nodeAffinityBytes if set.
	// +optional
	//
	// Deprecated: Marked as deprecated in pkg/estimator/pb/estimator.proto.
	NodeAffinity *v1.NodeSelector `protobuf:"bytes,1,opt,name=nodeAffinity,proto3,oneof" json:"nodeAffinity,omitempty"`
	// NodeSelector is a selector which must be true for the pod to fit on a node.
	// Selector which must match a node's labels for the pod to be scheduled on that node.
	// +optional
	NodeSelector map[string]string `protobuf:"bytes,2,rep,name=nodeSelector,proto3" json:"nodeSelector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// If specified, the pod's tolerations.
	// Deprecated: Writers should set this field and tolerationsBytes. Readers should prefer tolerationsBytes if set.
	// +optional
	//
	// Deprecated: Marked as deprecated in pkg/estimator/pb/estimator.proto.
	Tolerations []*v1.Toleration `protobuf:"bytes,3,rep,name=tolerations,proto3" json:"tolerations,omitempty"`
	// NodeAffinityBytes represents the node affinity in bytes.
	// NodeAffinityBytes is a proto-serialized corev1.NodeSelector object.
	// Generated by calling corev1.NodeSelector#Marshal().
	// Convertible to a corev1.NodeSelector object by calling corev1.NodeSelector#Unmarshal().
	// +optional
	NodeAffinityBytes []byte `protobuf:"bytes,4,opt,name=nodeAffinityBytes,proto3" json:"nodeAffinityBytes,omitempty"`
	// TolerationsBytes represents the tolerations in bytes.
	// Each item of tolerationsBytes is a proto-serialized corev1.Toleration object.
	// Generated by calling corev1.Toleration#Marshal().
	// Convertible to a corev1.Toleration object by calling corev1.Toleration#Unmarshal().
	// +optional
	TolerationsBytes [][]byte `protobuf:"bytes,5,rep,name=tolerationsBytes,proto3" json:"tolerationsBytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeClaim) Reset() {
	*x = NodeClaim{}
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeClaim) ProtoMessage() {}

func (x *NodeClaim) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeClaim.ProtoReflect.Descriptor instead.
func (*NodeClaim) Descriptor() ([]byte, []int) {
	return file_pkg_estimator_pb_estimator_proto_rawDescGZIP(), []int{6}
}

// Deprecated: Marked as deprecated in pkg/estimator/pb/estimator.proto.
func (x *NodeClaim) GetNodeAffinity() *v1.NodeSelector {
	if x != nil {
		return x.NodeAffinity
	}
	return nil
}

func (x *NodeClaim) GetNodeSelector() map[string]string {
	if x != nil {
		return x.NodeSelector
	}
	return nil
}

// Deprecated: Marked as deprecated in pkg/estimator/pb/estimator.proto.
func (x *NodeClaim) GetTolerations() []*v1.Toleration {
	if x != nil {
		return x.Tolerations
	}
	return nil
}

func (x *NodeClaim) GetNodeAffinityBytes() []byte {
	if x != nil {
		return x.NodeAffinityBytes
	}
	return nil
}

func (x *NodeClaim) GetTolerationsBytes() [][]byte {
	if x != nil {
		return x.TolerationsBytes
	}
	return nil
}

// ObjectReference contains enough information to locate the referenced object inside current cluster.
type ObjectReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// APIVersion represents the API version of the referent.
	// +required
	ApiVersion string `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	// Kind represents the Kind of the referent.
	// +required
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Namespace represents the namespace for the referent.
	// For non-namespace scoped resources(e.g. 'ClusterRole')，do not need specify Namespace,
	// and for namespace scoped resources, Namespace is required.
	// If Namespace is not specified, means the resource is non-namespace scoped.
	// +required
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Name represents the name of the referent.
	// +required
	Name          string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectReference) Reset() {
	*x = ObjectReference{}
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectReference) ProtoMessage() {}

func (x *ObjectReference) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectReference.ProtoReflect.Descriptor instead.
func (*ObjectReference) Descriptor() ([]byte, []int) {
	return file_pkg_estimator_pb_estimator_proto_rawDescGZIP(), []int{7}
}

func (x *ObjectReference) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ObjectReference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ObjectReference) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ObjectReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ReplicaRequirements represents the resource and scheduling requirements for each replica.
type ReplicaRequirements struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NodeClaim represents the NodeAffinity, NodeSelector and Tolerations required by each replica.
	// +optional
	NodeClaim *NodeClaim `protobuf:"bytes,1,opt,name=nodeClaim,proto3,oneof" json:"nodeClaim,omitempty"`
	// ResourceRequest represents the resources required by each replica.
	// Deprecated: Writers should set this field and resourceRequestBytes. Readers should prefer resourceRequestBytes if set.
	// +optional
	//
	// Deprecated: Marked as deprecated in pkg/estimator/pb/estimator.proto.
	ResourceRequest map[string]*resource.Quantity `protobuf:"bytes,2,rep,name=resourceRequest,proto3" json:"resourceRequest,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Namespace represents the namespaces belonged to a ResourceRequest
	// +optional
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// PriorityClassName represents the priority class name for a given ResourceRequest.
	// It is used by the resource quota estimator to check quota constraints, as ResourceQuota supports priority class as a scope.
	// +optional
	PriorityClassName string `protobuf:"bytes,4,opt,name=priorityClassName,proto3" json:"priorityClassName,omitempty"`
	// ResourceRequestBytes represents the resources required by each replica.
	// The value of map resourceRequestBytes is a proto-serialized resource.Quantity object.
	// Generated by calling resource.Quantity#Marshal().
	// Convertible to a resource.Quantity object by calling resource.Quantity#Unmarshal().
	// +optional
	ResourceRequestBytes map[string][]byte `protobuf:"bytes,5,rep,name=resourceRequestBytes,proto3" json:"resourceRequestBytes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ReplicaRequirements) Reset() {
	*x = ReplicaRequirements{}
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaRequirements) ProtoMessage() {}

func (x *ReplicaRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaRequirements.ProtoReflect.Descriptor instead.
func (*ReplicaRequirements) Descriptor() ([]byte, []int) {
	return file_pkg_estimator_pb_estimator_proto_rawDescGZIP(), []int{8}
}

func (x *ReplicaRequirements) GetNodeClaim() *NodeClaim {
	if x != nil {
		return x.NodeClaim
	}
	return nil
}

// Deprecated: Marked as deprecated in pkg/estimator/pb/estimator.proto.
func (x *ReplicaRequirements) GetResourceRequest() map[string]*resource.Quantity {
	if x != nil {
		return x.ResourceRequest
	}
	return nil
}

func (x *ReplicaRequirements) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ReplicaRequirements) GetPriorityClassName() string {
	if x != nil {
		return x.PriorityClassName
	}
	return ""
}

func (x *ReplicaRequirements) GetResourceRequestBytes() map[string][]byte {
	if x != nil {
		return x.ResourceRequestBytes
	}
	return nil
}

// UnschedulableReplicasRequest represents the request that sent by gRPC client to calculate unschedulable replicas.
type UnschedulableReplicasRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cluster represents the cluster name.
	// +required
	Cluster string `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// Resource represents the Kubernetes resource to be propagated.
	// +required
	Resource *ObjectReference `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// UnschedulableThreshold represents the period threshold of pod unschedulable condition.
	// This value is considered as a classification standard of unschedulable replicas.
	// +optional
	UnschedulableThreshold int64 `protobuf:"varint,3,opt,name=unschedulableThreshold,proto3" json:"unschedulableThreshold,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UnschedulableReplicasRequest) Reset() {
	*x = UnschedulableReplicasRequest{}
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnschedulableReplicasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnschedulableReplicasRequest) ProtoMessage() {}

func (x *UnschedulableReplicasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnschedulableReplicasRequest.ProtoReflect.Descriptor instead.
func (*UnschedulableReplicasRequest) Descriptor() ([]byte, []int) {
	return file_pkg_estimator_pb_estimator_proto_rawDescGZIP(), []int{9}
}

func (x *UnschedulableReplicasRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *UnschedulableReplicasRequest) GetResource() *ObjectReference {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *UnschedulableReplicasRequest) GetUnschedulableThreshold() int64 {
	if x != nil {
		return x.UnschedulableThreshold
	}
	return 0
}

// UnschedulableReplicasResponse represents the response that sent by gRPC server to calculate unschedulable replicas.
type UnschedulableReplicasResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UnschedulableReplicas represents the unschedulable replicas that the object contains.
	// +required
	UnschedulableReplicas int32 `protobuf:"varint,1,opt,name=unschedulableReplicas,proto3" json:"unschedulableReplicas,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UnschedulableReplicasResponse) Reset() {
	*x = UnschedulableReplicasResponse{}
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnschedulableReplicasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnschedulableReplicasResponse) ProtoMessage() {}

func (x *UnschedulableReplicasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_estimator_pb_estimator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnschedulableReplicasResponse.ProtoReflect.Descriptor instead.
func (*UnschedulableReplicasResponse) Descriptor() ([]byte, []int) {
	return file_pkg_estimator_pb_estimator_proto_rawDescGZIP(), []int{10}
}

func (x *UnschedulableReplicasResponse) GetUnschedulableReplicas() int32 {
	if x != nil {
		return x.UnschedulableReplicas
	}
	return 0
}

var File_pkg_estimator_pb_estimator_proto protoreflect.FileDescriptor

const file_pkg_estimator_pb_estimator_proto_rawDesc = "" +
	"\n" +
	" pkg/estimator/pb/estimator.proto\x12.github.com.karmada_io.karmada.pkg.estimator.pb\x1a\"k8s.io/api/core/v1/generated.proto\x1a4k8s.io/apimachinery/pkg/api/resource/generated.proto\"\xbb\x01\n" +
	"\tComponent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12~\n" +
	"\x13replicaRequirements\x18\x02 \x01(\v2L.github.com.karmada_io.karmada.pkg.estimator.pb.ComponentReplicaRequirementsR\x13replicaRequirements\x12\x1a\n" +
	"\breplicas\x18\x03 \x01(\x05R\breplicas\"\xa4\x05\n" +
	"\x1cComponentReplicaRequirements\x12\\\n" +
	"\tnodeClaim\x18\x01 \x01(\v29.github.com.karmada_io.karmada.pkg.estimator.pb.NodeClaimH\x00R\tnodeClaim\x88\x01\x01\x12\x8f\x01\n" +
	"\x0fresourceRequest\x18\x02 \x03(\v2a.github.com.karmada_io.karmada.pkg.estimator.pb.ComponentReplicaRequirements.ResourceRequestEntryB\x02\x18\x01R\x0fresourceRequest\x12,\n" +
	"\x11priorityClassName\x18\x03 \x01(\tR\x11priorityClassName\x12\x9a\x01\n" +
	"\x14resourceRequestBytes\x18\x04 \x03(\v2f.github.com.karmada_io.karmada.pkg.estimator.pb.ComponentReplicaRequirements.ResourceRequestBytesEntryR\x14resourceRequestBytes\x1ar\n" +
	"\x14ResourceRequestEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12D\n" +
	"\x05value\x18\x02 \x01(\v2..k8s.io.apimachinery.pkg.api.resource.QuantityR\x05value:\x028\x01\x1aG\n" +
	"\x19ResourceRequestBytesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_nodeClaim\"\xb5\x01\n" +
	" MaxAvailableComponentSetsRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12Y\n" +
	"\n" +
	"components\x18\x02 \x03(\v29.github.com.karmada_io.karmada.pkg.estimator.pb.ComponentR\n" +
	"components\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\"=\n" +
	"!MaxAvailableComponentSetsResponse\x12\x18\n" +
	"\amaxSets\x18\x01 \x01(\x05R\amaxSets\"\xae\x01\n" +
	"\x1bMaxAvailableReplicasRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12u\n" +
	"\x13replicaRequirements\x18\x02 \x01(\v2C.github.com.karmada_io.karmada.pkg.estimator.pb.ReplicaRequirementsR\x13replicaRequirements\"@\n" +
	"\x1cMaxAvailableReplicasResponse\x12 \n" +
	"\vmaxReplicas\x18\x01 \x01(\x05R\vmaxReplicas\"\xbd\x03\n" +
	"\tNodeClaim\x12M\n" +
	"\fnodeAffinity\x18\x01 \x01(\v2 .k8s.io.api.core.v1.NodeSelectorB\x02\x18\x01H\x00R\fnodeAffinity\x88\x01\x01\x12o\n" +
	"\fnodeSelector\x18\x02 \x03(\v2K.github.com.karmada_io.karmada.pkg.estimator.pb.NodeClaim.NodeSelectorEntryR\fnodeSelector\x12D\n" +
	"\vtolerations\x18\x03 \x03(\v2\x1e.k8s.io.api.core.v1.TolerationB\x02\x18\x01R\vtolerations\x12,\n" +
	"\x11nodeAffinityBytes\x18\x04 \x01(\fR\x11nodeAffinityBytes\x12*\n" +
	"\x10tolerationsBytes\x18\x05 \x03(\fR\x10tolerationsBytes\x1a?\n" +
	"\x11NodeSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\r_nodeAffinity\"w\n" +
	"\x0fObjectReference\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\xa7\x05\n" +
	"\x13ReplicaRequirements\x12\\\n" +
	"\tnodeClaim\x18\x01 \x01(\v29.github.com.karmada_io.karmada.pkg.estimator.pb.NodeClaimH\x00R\tnodeClaim\x88\x01\x01\x12\x86\x01\n" +
	"\x0fresourceRequest\x18\x02 \x03(\v2X.github.com.karmada_io.karmada.pkg.estimator.pb.ReplicaRequirements.ResourceRequestEntryB\x02\x18\x01R\x0fresourceRequest\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12,\n" +
	"\x11priorityClassName\x18\x04 \x01(\tR\x11priorityClassName\x12\x91\x01\n" +
	"\x14resourceRequestBytes\x18\x05 \x03(\v2].github.com.karmada_io.karmada.pkg.estimator.pb.ReplicaRequirements.ResourceRequestBytesEntryR\x14resourceRequestBytes\x1ar\n" +
	"\x14ResourceRequestEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12D\n" +
	"\x05value\x18\x02 \x01(\v2..k8s.io.apimachinery.pkg.api.resource.QuantityR\x05value:\x028\x01\x1aG\n" +
	"\x19ResourceRequestBytesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_nodeClaim\"\xcd\x01\n" +
	"\x1cUnschedulableReplicasRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12[\n" +
	"\bresource\x18\x02 \x01(\v2?.github.com.karmada_io.karmada.pkg.estimator.pb.ObjectReferenceR\bresource\x126\n" +
	"\x16unschedulableThreshold\x18\x03 \x01(\x03R\x16unschedulableThreshold\"U\n" +
	"\x1dUnschedulableReplicasResponse\x124\n" +
	"\x15unschedulableReplicas\x18\x01 \x01(\x05R\x15unschedulableReplicasB0Z.github.com/karmada-io/karmada/pkg/estimator/pbb\x06proto3"

var (
	file_pkg_estimator_pb_estimator_proto_rawDescOnce sync.Once
	file_pkg_estimator_pb_estimator_proto_rawDescData []byte
)

func file_pkg_estimator_pb_estimator_proto_rawDescGZIP() []byte {
	file_pkg_estimator_pb_estimator_proto_rawDescOnce.Do(func() {
		file_pkg_estimator_pb_estimator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_estimator_pb_estimator_proto_rawDesc), len(file_pkg_estimator_pb_estimator_proto_rawDesc)))
	})
	return file_pkg_estimator_pb_estimator_proto_rawDescData
}

var file_pkg_estimator_pb_estimator_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_estimator_pb_estimator_proto_goTypes = []any{
	(*Component)(nil),                         // 0: github.com.karmada_io.karmada.pkg.estimator.pb.Component
	(*ComponentReplicaRequirements)(nil),      // 1: github.com.karmada_io.karmada.pkg.estimator.pb.ComponentReplicaRequirements
	(*MaxAvailableComponentSetsRequest)(nil),  // 2: github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableComponentSetsRequest
	(*MaxAvailableComponentSetsResponse)(nil), // 3: github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableComponentSetsResponse
	(*MaxAvailableReplicasRequest)(nil),       // 4: github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableReplicasRequest
	(*MaxAvailableReplicasResponse)(nil),      // 5: github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableReplicasResponse
	(*NodeClaim)(nil),                         // 6: github.com.karmada_io.karmada.pkg.estimator.pb.NodeClaim
	(*ObjectReference)(nil),                   // 7: github.com.karmada_io.karmada.pkg.estimator.pb.ObjectReference
	(*ReplicaRequirements)(nil),               // 8: github.com.karmada_io.karmada.pkg.estimator.pb.ReplicaRequirements
	(*UnschedulableReplicasRequest)(nil),      // 9: github.com.karmada_io.karmada.pkg.estimator.pb.UnschedulableReplicasRequest
	(*UnschedulableReplicasResponse)(nil),     // 10: github.com.karmada_io.karmada.pkg.estimator.pb.UnschedulableReplicasResponse
	nil,                                       // 11: github.com.karmada_io.karmada.pkg.estimator.pb.ComponentReplicaRequirements.ResourceRequestEntry
	nil,                                       // 12: github.com.karmada_io.karmada.pkg.estimator.pb.ComponentReplicaRequirements.ResourceRequestBytesEntry
	nil,                                       // 13: github.com.karmada_io.karmada.pkg.estimator.pb.NodeClaim.NodeSelectorEntry
	nil,                                       // 14: github.com.karmada_io.karmada.pkg.estimator.pb.ReplicaRequirements.ResourceRequestEntry
	nil,                                       // 15: github.com.karmada_io.karmada.pkg.estimator.pb.ReplicaRequirements.ResourceRequestBytesEntry
	(*v1.NodeSelector)(nil),                   // 16: k8s.io.api.core.v1.NodeSelector
	(*v1.Toleration)(nil),                     // 17: k8s.io.api.core.v1.Toleration
	(*resource.Quantity)(nil),                 // 18: k8s.io.apimachinery.pkg.api.resource.Quantity
}
var file_pkg_estimator_pb_estimator_proto_depIdxs = []int32{
	1,  // 0: github.com.karmada_io.karmada.pkg.estimator.pb.Component.replicaRequirements:type_name -> github.com.karmada_io.karmada.pkg.estimator.pb.ComponentReplicaRequirements
	6,  // 1: github.com.karmada_io.karmada.pkg.estimator.pb.ComponentReplicaRequirements.nodeClaim:type_name -> github.com.karmada_io.karmada.pkg.estimator.pb.NodeClaim
	11, // 2: github.com.karmada_io.karmada.pkg.estimator.pb.ComponentReplicaRequirements.resourceRequest:type_name -> github.com.karmada_io.karmada.pkg.estimator.pb.ComponentReplicaRequirements.ResourceRequestEntry
	12, // 3: github.com.karmada_io.karmada.pkg.estimator.pb.ComponentReplicaRequirements.resourceRequestBytes:type_name -> github.com.karmada_io.karmada.pkg.estimator.pb.ComponentReplicaRequirements.ResourceRequestBytesEntry
	0,  // 4: github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableComponentSetsRequest.components:type_name -> github.com.karmada_io.karmada.pkg.estimator.pb.Component
	8,  // 5: github.com.karmada_io.karmada.pkg.estimator.pb.MaxAvailableReplicasRequest.replicaRequirements:type_name -> github.com.karmada_io.karmada.pkg.estimator.pb.ReplicaRequirements
	16, // 6: github.com.karmada_io.karmada.pkg.estimator.pb.NodeClaim.nodeAffinity:type_name -> k8s.io.api.core.v1.NodeSelector
	13, // 7: github.com.karmada_io.karmada.pkg.estimator.pb.NodeClaim.nodeSelector:type_name -> github.com.karmada_io.karmada.pkg.estimator.pb.NodeClaim.NodeSelectorEntry
	17, // 8: github.com.karmada_io.karmada.pkg.estimator.pb.NodeClaim.tolerations:type_name -> k8s.io.api.core.v1.Toleration
	6,  // 9: github.com.karmada_io.karmada.pkg.estimator.pb.ReplicaRequirements.nodeClaim:type_name -> github.com.karmada_io.karmada.pkg.estimator.pb.NodeClaim
	14, // 10: github.com.karmada_io.karmada.pkg.estimator.pb.ReplicaRequirements.resourceRequest:type_name -> github.com.karmada_io.karmada.pkg.estimator.pb.ReplicaRequirements.ResourceRequestEntry
	15, // 11: github.com.karmada_io.karmada.pkg.estimator.pb.ReplicaRequirements.resourceRequestBytes:type_name -> github.com.karmada_io.karmada.pkg.estimator.pb.ReplicaRequirements.ResourceRequestBytesEntry
	7,  // 12: github.com.karmada_io.karmada.pkg.estimator.pb.UnschedulableReplicasRequest.resource:type_name -> github.com.karmada_io.karmada.pkg.estimator.pb.ObjectReference
	18, // 13: github.com.karmada_io.karmada.pkg.estimator.pb.ComponentReplicaRequirements.ResourceRequestEntry.value:type_name -> k8s.io.apimachinery.pkg.api.resource.Quantity
	18, // 14: github.com.karmada_io.karmada.pkg.estimator.pb.ReplicaRequirements.ResourceRequestEntry.value:type_name -> k8s.io.apimachinery.pkg.api.resource.Quantity
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pkg_estimator_pb_estimator_proto_init() }
func file_pkg_estimator_pb_estimator_proto_init() {
	if File_pkg_estimator_pb_estimator_proto != nil {
		return
	}
	file_pkg_estimator_pb_estimator_proto_msgTypes[1].OneofWrappers = []any{}
	file_pkg_estimator_pb_estimator_proto_msgTypes[6].OneofWrappers = []any{}
	file_pkg_estimator_pb_estimator_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_estimator_pb_estimator_proto_rawDesc), len(file_pkg_estimator_pb_estimator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_estimator_pb_estimator_proto_goTypes,
		DependencyIndexes: file_pkg_estimator_pb_estimator_proto_depIdxs,
		MessageInfos:      file_pkg_estimator_pb_estimator_proto_msgTypes,
	}.Build()
	File_pkg_estimator_pb_estimator_proto = out.File
	file_pkg_estimator_pb_estimator_proto_goTypes = nil
	file_pkg_estimator_pb_estimator_proto_depIdxs = nil
}
