// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/estimator/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("pkg/estimator/pb/service.proto", fileDescriptor_f8ba5c092844dbe2) }

var fileDescriptor_f8ba5c092844dbe2 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0xc8, 0x4e, 0xd7,
	0x4f, 0x2d, 0x2e, 0xc9, 0xcc, 0x4d, 0x2c, 0xc9, 0x2f, 0xd2, 0x2f, 0x48, 0xd2, 0x2f, 0x4e, 0x2d,
	0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xd2, 0x4b, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcb, 0x4e, 0x2c, 0xca, 0x4d, 0x4c, 0x49, 0x8c, 0xcf,
	0xcc, 0x87, 0x31, 0xf5, 0x0a, 0xb2, 0xd3, 0xf5, 0xe0, 0xba, 0xf5, 0x0a, 0x92, 0xa4, 0x14, 0x30,
	0xcc, 0x4b, 0x4f, 0xcd, 0x4b, 0x2d, 0x4a, 0x2c, 0x49, 0x4d, 0x81, 0x98, 0x68, 0x74, 0x90, 0x91,
	0x8b, 0xd3, 0x15, 0xa6, 0x40, 0x68, 0x33, 0x23, 0x97, 0x88, 0x6f, 0x62, 0x85, 0x63, 0x59, 0x62,
	0x66, 0x4e, 0x62, 0x52, 0x4e, 0x6a, 0x50, 0x6a, 0x41, 0x4e, 0x66, 0x72, 0x62, 0xb1, 0x90, 0x37,
	0x89, 0x36, 0xeb, 0x61, 0x33, 0x25, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0xca, 0x87, 0x3a,
	0x86, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x2a, 0x31, 0x38, 0xb1, 0x44, 0x31, 0x15, 0x24, 0x01,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x73, 0xbd, 0x33, 0x3c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EstimatorClient is the client API for Estimator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EstimatorClient interface {
	MaxAvailableReplicas(ctx context.Context, in *MaxAvailableReplicasRequest, opts ...grpc.CallOption) (*MaxAvailableReplicasResponse, error)
}

type estimatorClient struct {
	cc *grpc.ClientConn
}

func NewEstimatorClient(cc *grpc.ClientConn) EstimatorClient {
	return &estimatorClient{cc}
}

func (c *estimatorClient) MaxAvailableReplicas(ctx context.Context, in *MaxAvailableReplicasRequest, opts ...grpc.CallOption) (*MaxAvailableReplicasResponse, error) {
	out := new(MaxAvailableReplicasResponse)
	err := c.cc.Invoke(ctx, "/github.com.karmada_io.karmada.pkg.estimator.pb.Estimator/MaxAvailableReplicas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EstimatorServer is the server API for Estimator service.
type EstimatorServer interface {
	MaxAvailableReplicas(context.Context, *MaxAvailableReplicasRequest) (*MaxAvailableReplicasResponse, error)
}

// UnimplementedEstimatorServer can be embedded to have forward compatible implementations.
type UnimplementedEstimatorServer struct {
}

func (*UnimplementedEstimatorServer) MaxAvailableReplicas(ctx context.Context, req *MaxAvailableReplicasRequest) (*MaxAvailableReplicasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaxAvailableReplicas not implemented")
}

func RegisterEstimatorServer(s *grpc.Server, srv EstimatorServer) {
	s.RegisterService(&_Estimator_serviceDesc, srv)
}

func _Estimator_MaxAvailableReplicas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaxAvailableReplicasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstimatorServer).MaxAvailableReplicas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.karmada_io.karmada.pkg.estimator.pb.Estimator/MaxAvailableReplicas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstimatorServer).MaxAvailableReplicas(ctx, req.(*MaxAvailableReplicasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Estimator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.karmada_io.karmada.pkg.estimator.pb.Estimator",
	HandlerType: (*EstimatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MaxAvailableReplicas",
			Handler:    _Estimator_MaxAvailableReplicas_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/estimator/pb/service.proto",
}
