/*
Copyright 2022 The Karmada Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package eventfilter

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"reflect"
	"strings"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	policyv1alpha1 "github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1"
)

// labelOrAnnoKeyPrefixByKarmada defines the key prefix used for labels or annotations used by karmada's own components.
const labelOrAnnoKeyPrefixByKarmada = ".karmada.io"

const specificationHashPrefix = "v1:sha256:"

// labelsForUserWithKarmadaPrefix enumerates special cases that labels use the karmada prefix but are really only for users to use.
var labelsForUserWithKarmadaPrefix = map[string]struct{}{
	policyv1alpha1.NamespaceSkipAutoPropagationLabel: {},
}

// SpecificationChanged check if the specification of the given object change or not
func SpecificationChanged(oldObj, newObj *unstructured.Unstructured) bool {
	return !reflect.DeepEqual(normalizedSpecification(oldObj), normalizedSpecification(newObj))
}

// GenerateResourceTemplateSpecificationHash returns a stable identity for source
// fields that can affect scheduling or Work delivery. Only status and fields
// generated by the API server are excluded.
func GenerateResourceTemplateSpecificationHash(object *unstructured.Unstructured) (string, error) {
	if object == nil {
		return "", fmt.Errorf("cannot hash a nil object")
	}
	data, err := json.Marshal(normalizedResourceTemplateSpecification(object).Object)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(data)
	return specificationHashPrefix + hex.EncodeToString(sum[:]), nil
}

// ResourceChangeByKarmada check if the change of the object is modified by Karmada.
// If oldObj deep equal to newObj after removing fields changed by Karmada, such change refers to ChangeByKarmada.
func ResourceChangeByKarmada(oldObj, newObj *unstructured.Unstructured) bool {
	oldBackup := oldObj.DeepCopy()
	newBackup := newObj.DeepCopy()

	removeIgnoredFields(oldBackup, newBackup)

	removeFieldsChangedByKarmada(oldBackup, newBackup)

	return reflect.DeepEqual(oldBackup, newBackup)
}

// removeIgnoredFields Remove the status and some system defined mutable fields in metadata, including managedFields and resourceVersion.
// Refer to https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/#ObjectMeta for more details.
func removeIgnoredFields(objects ...*unstructured.Unstructured) {
	removedFields := [][]string{{"status"}, {"metadata", "managedFields"}, {"metadata", "resourceVersion"}}
	for _, object := range objects {
		for _, field := range removedFields {
			unstructured.RemoveNestedField(object.Object, field...)
		}
	}
}

func normalizedSpecification(object *unstructured.Unstructured) *unstructured.Unstructured {
	normalized := object.DeepCopy()
	removeIgnoredFields(normalized)
	return normalized
}

func normalizedResourceTemplateSpecification(object *unstructured.Unstructured) *unstructured.Unstructured {
	normalized := object.DeepCopy()
	removedFields := [][]string{
		{"status"},
		{"metadata", "resourceVersion"},
		{"metadata", "managedFields"},
		{"metadata", "generation"},
		{"metadata", "creationTimestamp"},
		{"metadata", "deletionTimestamp"},
		{"metadata", "deletionGracePeriodSeconds"},
		{"metadata", "uid"},
	}
	for _, field := range removedFields {
		unstructured.RemoveNestedField(normalized.Object, field...)
	}
	return normalized
}

// removeFieldsChangedByKarmada Remove the fields modified by karmada's own components.
func removeFieldsChangedByKarmada(oldBackup, newBackup *unstructured.Unstructured) {
	// Remove label or annotations changed by Karmada
	removeLabelOrAnnotationByKarmada(oldBackup)
	removeLabelOrAnnotationByKarmada(newBackup)

	// Karmada's change may result in some auto-generated fields being modified indirectly, e.g: metadata.generation
	// They should also be removed before comparing.
	removedFields := [][]string{{"metadata", "generation"}}
	for _, r := range removedFields {
		unstructured.RemoveNestedField(oldBackup.Object, r...)
		unstructured.RemoveNestedField(newBackup.Object, r...)
	}
}

// removeLabelOrAnnotationByKarmada remove the label or annotation modified by karmada's own components.
func removeLabelOrAnnotationByKarmada(unstructuredObj *unstructured.Unstructured) {
	for k := range unstructuredObj.GetLabels() {
		_, isLabelForUser := labelsForUserWithKarmadaPrefix[k]
		if strings.Contains(k, labelOrAnnoKeyPrefixByKarmada) && !isLabelForUser {
			unstructured.RemoveNestedField(unstructuredObj.Object, []string{"metadata", "labels", k}...)
		}
	}
	if len(unstructuredObj.GetLabels()) == 0 {
		unstructured.RemoveNestedField(unstructuredObj.Object, []string{"metadata", "labels"}...)
	}

	for k := range unstructuredObj.GetAnnotations() {
		if strings.Contains(k, labelOrAnnoKeyPrefixByKarmada) {
			unstructured.RemoveNestedField(unstructuredObj.Object, []string{"metadata", "annotations", k}...)
		}
	}
	if len(unstructuredObj.GetAnnotations()) == 0 {
		unstructured.RemoveNestedField(unstructuredObj.Object, []string{"metadata", "annotations"}...)
	}
}
