apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: karmada-general-ca
  namespace: cert-manager
spec:
  commonName: kubernetes-ca
  duration: 43800h0m0s
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: karmada-root-ca
  privateKey:
    algorithm: ECDSA
    size: 384
  renewBefore: 2190h0m0s
  secretName: karmada-general-ca
  usages:
  - signing
