apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: karmada-root
  namespace: cert-manager
spec:
  commonName: Karmada Root CA
  duration: 131400h0m0s
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-cluster
  privateKey:
    algorithm: ECDSA
    size: 384
  renewBefore: 4368h0m0s
  secretName: karmada-root
  usages:
  - signing
