apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: karmada-controller-manager
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
    - '*'
    verbs: ["get", "watch", "list", "create", "update", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "create", "update", "delete"]
