---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  creationTimestamp: null
  name: propagationbindings.propagationstrategy.karmada.io
spec:
  group: propagationstrategy.karmada.io
  names:
    kind: PropagationBinding
    listKind: PropagationBindingList
    plural: propagationbindings
    singular: propagationbinding
  scope: Namespaced
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---