apiVersion: v1
kind: Secret
metadata:
  name: karmada-cert-secret
  namespace: karmada-system
type: Opaque
data:
  server-ca.crt: |
    {{ca_crt}}
  karmada.crt: |
    {{client_cer}}
  karmada.key: |
    {{client_key}}

