apiVersion: v1
kind: Secret
metadata:
  name: karmada-cert-secret
  namespace: karmada-system
type: Opaque
data:
  server-ca.crt: |
    {{ca_crt}}
  karmada.crt: |
    {{client_cer}}
  karmada.key: |
    {{client_key}}
  front-proxy-ca.crt: |
    {{front_proxy_ca_crt}}
  front-proxy-client.crt: |
    {{front_proxy_client_crt}}
  front-proxy-client.key: |
    {{front_proxy_client_key}}
