apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
  namespace: karmada-system
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ca_crt}}
  tls.key: |
    {{ca_key}}
---
# server.crt: mainly used as server certificate for karmada components, such as karmada-apiserver, karmada-search, karmada-metrics-adapter, etc.
apiVersion: v1
kind: Secret
metadata:
  name: server-cert
  namespace: karmada-system
type: kubernetes.io/tls
data:
  ca.crt: |
    {{ca_crt}}
  tls.crt: |
    {{server_crt}}
  tls.key: |
    {{server_key}}
---
# client.crt: mainly used to construct kubeconfig for other components to access karmada-apiserver.
apiVersion: v1
kind: Secret
metadata:
  name: client-cert
  namespace: karmada-system
type: kubernetes.io/tls
data:
  ca.crt: |
    {{ca_crt}}
  tls.crt: |
    {{client_crt}}
  tls.key: |
    {{client_key}}
---
apiVersion: v1
kind: Secret
metadata:
  name: front-proxy-client-cert
  namespace: karmada-system
type: kubernetes.io/tls
data:
  ca.crt: |
    {{ca_crt}}
  tls.crt: |
    {{front_proxy_client_crt}}
  tls.key: |
    {{front_proxy_client_key}}
---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-server-cert
  namespace: karmada-system
type: kubernetes.io/tls
data:
  ca.crt: |
    {{ca_crt}}
  tls.crt: |
    {{etcd_server_crt}}
  tls.key: |
    {{etcd_server_key}}
---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-client-cert
  namespace: karmada-system
type: kubernetes.io/tls
data:
  ca.crt: |
    {{ca_crt}}
  tls.crt: |
    {{etcd_client_crt}}
  tls.key: |
    {{etcd_client_key}}
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  namespace: karmada-system
type: kubernetes.io/tls
data:
  ca.crt: |
    {{ca_crt}}
  tls.crt: |
    {{webhook_server_crt}}
  tls.key: |
    {{webhook_server_key}}
