apiVersion: v1
kind: ServiceAccount
metadata:
  name: karmada-controller-manager
  namespace: karmada-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: karmada-scheduler
  namespace: karmada-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: karmada-webhook
  namespace: karmada-system
