/*
Copyright 2022 The Karmada Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	cliflag "k8s.io/component-base/cli/flag"
)

const optionsFenceHeading = "### Options\n\n```\n"

// patchOptsFromHelp replaces the first ### Options fence in md with component-base grouped flags from cmd.Help() when available; otherwise returns md unchanged.
func patchOptsFromHelp(md string, cmd *cobra.Command) string {
	cmd.InitDefaultHelpCmd()
	cmd.InitDefaultCompletionCmd()
	cmd.SetGlobalNormalizationFunc(cliflag.WordSepNormalizeFunc)

	var hb bytes.Buffer
	out, errOut := cmd.OutOrStdout(), cmd.ErrOrStderr()
	cmd.SetOut(&hb)
	cmd.SetErr(&hb)
	if err := cmd.Help(); err != nil {
		cmd.SetOut(out)
		cmd.SetErr(errOut)
		return md
	}
	cmd.SetOut(out)
	cmd.SetErr(errOut)
	s := hb.String()
	tail := ""
	const usagePrefix = "Usage:\n  "
	if _, after, ok := strings.Cut(s, usagePrefix); ok {
		if _, rest, ok2 := strings.Cut(after, "\n"); ok2 {
			tail = strings.TrimSpace(rest)
		}
	}
	if !strings.Contains(tail, " flags:\n") {
		return md
	}
	// Replace body of first ### Options ```...``` block: [lo, lo+rel) is old PrintDefaults text.
	lo := strings.Index(md, optionsFenceHeading)
	if lo < 0 {
		return md
	}
	lo += len(optionsFenceHeading)
	rel := strings.Index(md[lo:], "\n```")
	if rel < 0 {
		return md
	}
	return md[:lo] + tail + md[lo+rel:]
}

// MarkdownPostProcessing reads each generated .md (same walk as doc.GenMarkdownTree), runs patchOptsFromHelp, then processor.
func MarkdownPostProcessing(cmd *cobra.Command, dir string, processor func(string) string) error {
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		if err := MarkdownPostProcessing(c, dir, processor); err != nil {
			return err
		}
	}

	basename := strings.ReplaceAll(cmd.CommandPath(), " ", "_") + ".md"
	filename := filepath.Join(dir, basename)

	// Remove the markdown file for the version subcommand
	if strings.Contains(basename, "version") {
		return os.Remove(filename)
	}

	markdownBytes, err := os.ReadFile(filename)
	if err != nil {
		return err
	}

	md := patchOptsFromHelp(string(markdownBytes), cmd)
	processedMarkDown := processor(md)

	return os.WriteFile(filename, []byte(processedMarkDown), 0600)
}

// cleanupForInclude parts of markdown that will make difficult to use it as include in the website:
// - The section before synopsis.
// - The sections see also.
func cleanupForInclude(md string) string {
	lines := strings.Split(md, "\n")

	// add title for component docs
	firstL := lines[0]
	title := strings.TrimPrefix(firstL, "## ")
	lines[0] = "---"
	newlines := []string{"---", "title: " + title}
	newlines = append(newlines, lines...)

	var cleanMd strings.Builder
	for i, line := range newlines {
		if line == "### SEE ALSO" {
			break
		}

		cleanMd.WriteString(line)
		if i < len(newlines)-1 {
			cleanMd.WriteString("\n")
		}
	}

	cleanMd.WriteString("###### Auto generated by [spf13/cobra script in Karmada](https://github.com/karmada-io/karmada/tree/master/hack/tools/gencomponentdocs)")
	return cleanMd.String()
}
