#!/usr/bin/env python3
"""
extract_crd_schema.py — turn a Karmada policy CRD into an LLM-friendly schema doc.

The output is two Markdown files (10-propagation-schema.md, 11-override-schema.md) that
list every field, its type, whether it is required, and its description. The agent
reads these instead of trying to guess the schema, and they are regenerated on every
CRD bump so the knowledge stays in lockstep with the code.

Usage:
    extract_crd_schema.py \\
        --crd charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml \\
        --out hack/agent-skills/knowledge/10-propagation-schema.md \\
        --title "PropagationPolicy"

The script is intentionally dependency-light (PyYAML only) so it can run in CI without
a venv setup step. It is deterministic: same CRD in → same Markdown out, byte-for-byte.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml


GENERATED_BANNER = (
    "<!--\n"
    "AUTO-GENERATED by hack/agent-skills/scripts/extract_crd_schema.py.\n"
    "Do not edit by hand. Re-run the script after CRD changes:\n"
    "  python3 hack/agent-skills/scripts/extract_crd_schema.py \\\n"
    "      --crd <path-to-crd> --out <this-file> --title <Kind>\n"
    "-->\n"
)


def load_openapi_schema(crd_path: Path) -> dict[str, Any]:
    doc = yaml.safe_load(crd_path.read_text())
    if doc.get("kind") != "CustomResourceDefinition":
        raise SystemExit(f"{crd_path} is not a CRD")
    versions = doc["spec"]["versions"]
    if len(versions) != 1:
        raise SystemExit(
            f"expected exactly one version; found {[v['name'] for v in versions]}"
        )
    return versions[0]["schema"]["openAPIV3Schema"]


def walk(schema: dict[str, Any], path: str, required_here: set[str]) -> list[dict]:
    """Flatten an OpenAPI schema into a list of {path, type, required, desc} rows.

    We deliberately stop descending at depth-3 leaves. Going deeper produces a wall of
    rows nobody (LLM or human) will read; the top three levels are what determines
    whether a generated YAML is structurally correct.
    """
    rows: list[dict] = []
    properties = schema.get("properties", {}) or {}
    nested_required = set(schema.get("required", []) or [])
    for name, prop in properties.items():
        sub_path = f"{path}.{name}" if path else name
        is_required = name in nested_required
        rows.append(_row(sub_path, prop, is_required))
        if prop.get("type") == "object" and "properties" in prop and sub_path.count(".") < 3:
            rows.extend(walk(prop, sub_path, nested_required))
        elif prop.get("type") == "array" and isinstance(prop.get("items"), dict):
            items = prop["items"]
            if items.get("type") == "object" and "properties" in items and sub_path.count(".") < 3:
                rows.extend(walk(items, f"{sub_path}[]", set()))
    return rows


def _row(path: str, prop: dict[str, Any], required: bool) -> dict:
    typ = prop.get("type", "object")
    if typ == "array":
        items = prop.get("items", {})
        typ = f"array<{items.get('type', 'object')}>"
    enum = prop.get("enum")
    if enum:
        typ = f"{typ} (enum: {', '.join(map(str, enum))})"
    default = prop.get("default")
    if default is not None:
        typ = f"{typ} (default: {default})"
    desc = (prop.get("description") or "").strip().replace("\n", " ")
    if len(desc) > 240:
        desc = desc[:237].rstrip() + "..."
    return {"path": path, "type": typ, "required": required, "desc": desc}


def render_markdown(title: str, rows: list[dict]) -> str:
    out: list[str] = [
        GENERATED_BANNER,
        f"# {title} — Schema Reference\n",
        "Each row below is one field path in the CRD's OpenAPI v3 schema. The agent\n"
        "should treat this file as authoritative when picking field names, types, and\n"
        "enum values. Descriptions are copied verbatim from the CRD.\n",
        "| Field path | Type | Required | Description |",
        "|------------|------|----------|-------------|",
    ]
    for row in rows:
        path = "`" + row["path"] + "`"
        typ = "`" + row["type"] + "`"
        req = "yes" if row["required"] else "no"
        desc = row["desc"].replace("|", "\\|") or "—"
        out.append(f"| {path} | {typ} | {req} | {desc} |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--crd", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--title", required=True)
    args = ap.parse_args()

    if not args.crd.exists():
        print(f"CRD not found: {args.crd}", file=sys.stderr)
        return 1

    schema = load_openapi_schema(args.crd)
    rows = walk(schema, "", set())
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_markdown(args.title, rows))
    print(f"wrote {len(rows)} field rows → {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
