apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: karmada-operator
  labels:
    karmada-app: karmada-operator
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - operator.karmada.io
    resources:
      - karmadas
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - operator.karmada.io
    resources:
      - karmadas/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
    verbs:
      - get
      - create
      - update
      - delete
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
    verbs:
      - get
      - create
      - update
      - delete
