apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: bad-4
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: example
  association: true
  placement:
    clusterAffinity:
      clusterNames: [member1]
  failover:
    application:
      decisionConditions:
        tolerationSeconds: 30
      purgeMode: Immediately
