apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: bad-6
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: example
  placement:
    clusterAffinity:
      clusterNames: [member1, member2]
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames: [member1]
            weight: 0.6
          - targetCluster:
              clusterNames: [member2]
            weight: 0.4
