apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: bad-2
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: example
  overrideRules:
    - targetCluster:
        clusterNames: [member2]
      overriders:
        plaintext:
          - path: $.spec.template.spec.containers[0].image
            operator: replace
            value: nginx:alpine
