apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: bad-1
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: example
  replicaScheduling:
    replicaSchedulingType: Duplicated
  placement:
    clusterAffinity:
      clusterNames: [member1]
