apiVersion: policy.karmada.io/v1alpha1
kind: ClusterOverridePolicy
metadata:
  name: example-cluster-override
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
      namespace: default
  targetCluster:
    clusterNames:
      - member1
  overriders:
    plaintext:
      - operator: replace
        path: /spec/replicas
        value: 1
