apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: example-policy
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
      labelSelector:
        matchLabels:
          a: b
  association: false
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster3
      exclude:
        - cluster1
    spreadConstraints:
      - spreadByLabel: failuredomain.kubernetes.io/zone
        maxGroups: 3
        minGroups: 3
  schedulerName: default
