apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
      fieldSelector:
        matchExpressions:
          - key: provider
            operator: In
            values:
              - huaweicloud
          - key: region
            operator: NotIn
            values:
              - cn-south-1
