name: released chart to DockerHub
on:
  release:
    types:
      - published
permissions:
  contents: read
jobs:
  publish-chart-to-dockerhub:
    name: publish to DockerHub
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          # fetch-depth:
          # 0 indicates all history for all branches and tags.
          # for `git describe --tags` in Makefile.
          fetch-depth: 0
      - name: install Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
      - name: login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: package chart
        env:
          VERSION: ${{ github.ref_name }}
        run: make package-chart
      - name: push chart
        env:
          VERSION: ${{ github.ref_name }}
        run: make push-chart
