name: released chart to DockerHub
on:
  release:
    types:
      - published
permissions:
  contents: read
jobs:
  publish-chart-to-dockerhub:
    name: publish to DockerHub
    runs-on: ubuntu-22.04
    # prevent job running from forked repository, otherwise
    # 1. running on the forked repository would fail as missing necessary secret.
    # 2. running on the forked repository would use unnecessary GitHub Action time.
    if: ${{ github.repository == 'karmada-io/karmada' }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          # fetch-depth:
          # 0 indicates all history for all branches and tags.
          # for `git describe --tags` in Makefile.
          fetch-depth: 0
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: package chart
        env:
          VERSION: ${{ github.ref_name }}
        run: make package-chart
      - name: push chart
        env:
          VERSION: ${{ github.ref_name }}
        run: make push-chart
