name: released chart to DockerHub
on:
  release:
    types:
      - published
jobs:
  publish-chart-to-dockerhub:
    name: publish to DockerHub
    permissions:
      id-token: write # To be able to get OIDC ID token to sign images.
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          # fetch-depth:
          # 0 indicates all history for all branches and tags.
          # for `git describe --tags` in Makefile.
          fetch-depth: 0
      - name: login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.0.3
        with:
          cosign-release: 'v1.13.1'
      - name: package chart
        env:
          VERSION: ${{ github.ref_name }}
        run: make package-chart
      - name: push chart
        env:
          VERSION: ${{ github.ref_name }}
          SIGN_IMAGE: 1
          COSIGN_EXPERIMENTAL: 1
        run: make push-chart
