name: Release Images
on:
  release:
    types:
      - published
jobs:
  release-image:
    name: release images
    strategy:
      matrix:
        target:
          - karmada-aggregated-apiserver
          - karmada-controller-manager 
          - karmada-scheduler
          - karmada-webhook
          - karmada-agent
          - karmada-scheduler-estimator
          - karmada-interpreter-webhook-example
    runs-on: ubuntu-18.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.REPO_USERNAME }}
          password: ${{ secrets.REPO_PASSWORD }}        
      - name: prepare context for buildx
        run: cp cluster/images/general/Dockerfile ..
      - name: prepare Dokerfile
        run: sed -i 's/_TARGET_/${{ matrix.target }}/g' ../Dockerfile
      - name: build and push
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --build-arg TARGET=${{ matrix.target }} \
            -t ${{ secrets.REPO }}/${{ matrix.target }}:${{ github.ref_name }} \
            ..
